_prefs: 
  saveCenter: true
_properties: 
  bridge: 
    "group-by": layer
attribution: Map data © OpenStreetMap contributors
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -73.98073196411133
  - 40.75892792712664
  - 15
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
mtime: 1395694959918
name: OSM Bright 2
scale: 1
source: "mapbox:///mapbox.mapbox-streets-v42-dev"
styles: 
  - style.mss
  - road.mss
  - labels.mss
template: ''
